// frontend-vue/src/App.vue
<script setup>
import { ref } from 'vue';
import { ApiService } from './services/api';
import LoginPage from './pages/LoginPage.vue';
import DashboardPage from './pages/DashboardPage.vue';

const isAuth = ref(ApiService.isAuthenticated());

const handleLogout = () => {
  ApiService.clearToken();
  isAuth.value = false;
};
</script>

<template>
  <LoginPage v-if="!isAuth" @loginSuccess="isAuth = true" />
  <DashboardPage v-else @logout="handleLogout" />
</template>

// frontend-react/src/App.jsx
import { useState } from 'react';
import { ApiService } from './services/api';
import { LoginPage } from './pages/LoginPage';
import { DashboardPage } from './pages/DashboardPage';

const App = () => {
  const [isAuth, setIsAuth] = useState(ApiService.isAuthenticated());

  const handleLogout = () => {
    ApiService.clearToken();
    setIsAuth(false);
  };

  if (!isAuth) {
    return <LoginPage onLoginSuccess={() => setIsAuth(true)} />;
  }

  return <DashboardPage onLogout={handleLogout} />;
};

export default App;
